apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: model-service

  template:
    metadata:
      labels:
        app: model-service

    spec:
      containers:
        - name: model-service
          image: wyccsc/k8s_model_service:1.0.0
          ports:
            - containerPort: 8000